### PR TITLE
Updated channel and documentation to Rubocop v1.8.1

### PR DESCRIPTION
**Pull request by DanielWright**
As usual, I'll create the correct base branch and update the PR before merging.

### CODE REVIEW

**Review by filipesperandio — APPROVED** [review]

**Comment by DanielWright** [comment]
@filipesperandio I realize I made a minor mistake (maybe?) when I merged the last update. The Rubocop version was v1.7.0, but I merged the update to `channel/rubocop-1-70`, which would correspond to Rubocop v1.70. I'm going to merge this one as `channel/rubocop-1-8-1`, and hope very hard that Rubocop doesn't end up releasing v1.70 at some point some years from now. 😅🤞

**Comment by filipesperandio** [comment]
@DanielWright thanks for the heads up. I still had to stare at it for a few seconds to understand the difference 🙈 
I think this is OK as is, and if they ever release a 1.70 version we won't care much old ones, guess we are fine.

**Comment by filipesperandio** [comment]
@DanielWright I am also adding a `channel/rubocop-1-7-0` so we gonna have both (`channel-rubocop-1-7-0` and `channel-rubocop-1-70`) pointing at version `v1.7.0`.
`v1.8.0` will be `channel/rubocop-1-8-0` as expected.

**Comment by DanielWright** [comment]
@filipesperandio Sounds good. Sorry if my explanation was a bit opaque! Hopefully this will be the last of the oddities from the 1.x version change.

**Comment by filipesperandio** [comment]
@DanielWright Nah, it was fine and no worries. All good.

**Pull request merged**
