### PR TITLE
[Channel 0-80] Update rubocop (0.80.1) (patch update)

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by krzysiek1507** [comment]
@filipesperandio could you please take a look?

**Comment by filipesperandio** [comment]
Have you ran this through `bin/newver`, it usually also includes new docs and so... It might be that there is none, just confirming.

**Comment by krzysiek1507** [comment]
I just ran it.

It looks like the `latest` image is quite old and uses Ruby 2.5 so could you please build one and push to docker hub?

**Comment by krzysiek1507** [comment]
Should I `bundle update` to update all of the deps?

**Comment by filipesperandio** [comment]
@krzysiek1507 We usually ran it from the most recent channel.

**Comment by krzysiek1507** [comment]
@filipesperandio this is not a minor 0.81.0 update. It's it a patch 0.80.1.

**Comment by krzysiek1507** [comment]
@filipesperandio I changed back the base branch.

**Comment by filipesperandio** [comment]
Ugh! My confusion.

**Comment by krzysiek1507** [comment]
Thanks!

**Comment by krzysiek1507** [comment]
How much time do you need to deploy it?

**Comment by krzysiek1507** [comment]
It looks like it's deployed!

**Comment by filipesperandio** [comment]
It became available to the CLI a few minutes after the merge and was deployed to .com in the afternoon! 👍

**Comment by krzysiek1507** [comment]
Thanks! Let me know if I can help with anything.

**Pull request merged**
