### PR TITLE
Updated channel and documentation to Rubocop v0.82.0

### PR DESCRIPTION
**Pull request by DanielWright**

### CODE REVIEW

**Comment by DanielWright** [comment]
Gentle nudge about this PR. 😃

**Comment by severin** [comment]
Version 0.82 was released more than two weeks ago: https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0820-2020-04-16

Would be great to get this channel merged 😉

**Comment by rkorzeniec** [comment]
@efueger is there any chance for you to look into this PR?

**Comment by efueger** [comment]
Hi @DanielWright  - devs are checking this and the 0.83 update now! We'll have an update soon. 👌

**Pull request merged**
