### PR TITLE
Add channel/rubocop-1-12-1

### PR DESCRIPTION
**Pull request by timlkelly**
Currently targeting `channel/rubocop-1-12-0` because I do not see `channel/rubocop-1-12-1`.

### CODE REVIEW

**Comment by fede-moya** [comment]
Branch [channel/rubocop-1-12-1](https://github.com/codeclimate/codeclimate-rubocop/tree/channel/rubocop-1-12-1) exists now. Could you try rebasing this one now ?

**Comment by fede-moya** [comment]
@timlkelly What I'm doing for updating the fork properly something similar to what appears [on this article](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a ), let me know if you need some help with that.

**Comment by timlkelly** [comment]
Yes, I was attempting to follow that article as well. I wonder if I am having issues because of the rewritten history.

```
~/development/ruby/gems/codeclimate-rubocop channel/rubocop-1-12-1 ❯ git remote -v
origin  git@github.com:timlkelly/codeclimate-rubocop.git (fetch)
origin  git@github.com:timlkelly/codeclimate-rubocop.git (push)
upstream        git@github.com:codeclimate/codeclimate-rubocop.git (fetch)
upstream        git@github.com:codeclimate/codeclimate-rubocop.git (push)
~/development/ruby/gems/codeclimate-rubocop channel/rubocop-1-12-1 ❯ git fetch upstream
~/development/ruby/gems/codeclimate-rubocop channel/rubocop-1-12-1 ❯ git rebase upstream/channel/rubocop-1-12-1
Current branch channel/rubocop-1-12-1 is up to date.
~/development/ruby/gems/codeclimate-rubocop channel/rubocop-1-12-1 ❯ git pull upstream channel/rubocop-1-12-1
From github.com:codeclimate/codeclimate-rubocop
 * branch            channel/rubocop-1-12-1 -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.
```

**Comment by timlkelly** [comment]
Okay, I removed the remote and re-added it and everything seems to be working now.

**Review by fede-moya — APPROVED** [review]
Great 👍🏼 . I think we can move forward and update the pr for 1.18.3 and skip the update for previous versions if needed WDYT ?

**Comment by timlkelly** [comment]
@fede-moya I'm fine to close the other versions if that's okay and focus on 1.18.3. I didn't know if you wanted the incremental updating or just jump straight to current.

**Comment by fede-moya** [comment]
@timlkelly Cool, let's update `1.18.3` then. I wasn't sure, I have now just discussed it with a colleague and we agreed to go straight to latest and add previous is demanded.

**Pull request merged**
