### PR TITLE
Update rubocop to 1.46.0

### PR DESCRIPTION
**Pull request by BrianHawley**
- General bundle update.
- Update the docs too.

### CODE REVIEW

**Comment by BrianHawley** [comment]
@fede-moya or @filipesperandio could you review and merge?

**Review by fede-moya — APPROVED** [review]

**Comment by BrianHawley** [comment]
@fede-moya, @filipesperandio, since this wasn't merged, a new version had time to come out, so I updated it. Could you merge this and deploy the new channel/beta?

**Comment by BrianHawley** [comment]
@fede-moya or @filipesperandio could you review and merge?

**Comment by BrianHawley** [comment]
@fede-moya or @filipesperandio could you review and merge?

**Comment by BrianHawley** [comment]
@fede-moya I don't have merge privileges in this repo, so approving the PR isn't enough. Who do I ask to get this merged?

**Pull request merged**
