### PR TITLE
Updated channel and documentation to Rubocop v0.86.0

### PR DESCRIPTION
**Pull request by DanielWright**
This PR proposes to update the Rubocop integration to support v0.85.1.

### CODE REVIEW

**Comment by efueger** [comment]
Thanks @DanielWright! Adding this to the engineering queue. 👍

**Comment by DanielWright** [comment]
Hi @efueger, I'm curious if there's any update here? 😄

**Comment by alexander-makarenko** [comment]
In the meantime, [rubocop 0.86](https://github.com/rubocop-hq/rubocop/releases) has been released. @DanielWright Would be amazing if you could update your PR to support it.

**Comment by DanielWright** [comment]
I've updated the PR for 0.86.

**Comment by filipesperandio** [comment]
@DanielWright Hey! Do you mind rebasing with `channel/rubocop-0-86` branch? I can merge it in right after that.

**Pull request merged**
