### PR TITLE
Add rubocop-performance back

### PR DESCRIPTION
**Pull request by filipesperandio**

### CODE REVIEW

**Comment by Mange** [comment]
I'd love to get this into `rubocop-0-71` too. :see_no_evil: 
(In addition to `rubocop-rails` #188)

**Comment by filipesperandio** [comment]
@Mange https://github.com/codeclimate/codeclimate-rubocop/pull/192
Will look into `rubocop-rails` next.

**Comment by aleksandrlat** [comment]
Could you guys please merge this?

**Comment by filipesperandio** [comment]
RE: #187 and https://github.com/codeclimate-support/escalations/issues/634

**Pull request merged**
