### PR TITLE
Updated channel and documentation to Rubocop v0.92.0

### PR DESCRIPTION
**Pull request by DanielWright**

### CODE REVIEW

**Comment by DanielWright** [comment]
Well, that didn't work. Lemme try again. 🤦

**Comment by DanielWright** [comment]
Sorry about that. 😅

**Comment by DanielWright** [comment]
Would love a CR here this first time, to validate I'm following the workflow correctly!

**Review by filipesperandio — APPROVED** [review]
Yeah, that's pretty much it.
Pushing up a branch for the new channel with the latest available, then opening up a PR with the changes.

**Comment by filipesperandio** [comment]
Thanks, @DanielWright !

Being to the platform.

**Pull request merged**
