### PR TITLE
Add channel/rubocop-1-12-0

### PR DESCRIPTION
**Pull request by timlkelly**
- Adds channel/rubocop-1-12-0

@fede-moya I don't know if I got ahead of myself and maybe these channels shouldn't be created until #279 is merged? Or I think they may need to be rebased after the merge. 

This currently includes the work in #279 because I used that to branch from.

### CODE REVIEW

**Comment by fede-moya** [comment]
@timlkelly they just need to be merge. Will be starting to merge tomorrow.

**Comment by timlkelly** [comment]
Okay, thank you. Can you make a 1.12.1 branch? I think that's the only one
that is missing.

**Comment by fede-moya** [comment]
@timlkelly done !

**Comment by timlkelly** [comment]
Apologies, but I'm not seeing `channel/rubocop-1-12-1`. I've pointed #281 to `channel/rubocop-1-12-0` in the meantime.

**Comment by fede-moya** [comment]
@timlkelly can you rebase this one now ? 🙏🏼

**Comment by timlkelly** [comment]
@fede-moya apologies I'm not sure if I rebased this correctly. I am still seeing the merge conflicts on Github but not locally. If I try to rebase again it says everything is up to date. Does the `codeclimate:channel/rubocop-1-12-0` itself need to be rebased?

**Comment by fede-moya** [comment]
@timlkelly I cloned your fork and I rebased properly. I think you just didn't fetch upstream before rebasing.

**Comment by timlkelly** [comment]
Okay, thank you. I will try doing that properly for the next rebase.

**Pull request merged**
