### PR TITLE
Update rubocop to 1.28.1

### PR DESCRIPTION
**Pull request by BrianHawley**
- General bundle update.
- Update the docs too.

### CODE REVIEW

**Comment by BrianHawley** [comment]
@fede-moya or @filipesperandio can you merge this one?

**Comment by fede-moya** [comment]
@BrianHawley We will be looking at this one next week 👍🏼

**Comment by filipemendespi** [comment]
> @BrianHawley We will be looking at this one next week 👍🏼

Do you have any updates on when it comes out? Thanks.

**Comment by BrianHawley** [comment]
@filipemendespi when what comes out? I'm just running bundle update on this PR while I'm waiting for you. It can be merged at any time.

**Comment by filipemendespi** [comment]
> @filipemendespi when what comes out? I'm just running bundle update on this PR while I'm waiting for you. It can be merged at any time. This is targeting the beta channel, so you don't have to do new codeclimate releases to merge PRs to that channel. You just merge them.

I don't know if I understood your message correctly, but are you assuming that I'm part of the CodeClimate team?

**Comment by BrianHawley** [comment]
@fede-moya any luck getting time to merge this one?

**Comment by BrianHawley** [comment]
@fede-moya or @filipesperandio can you merge this one?

**Pull request merged**
