### PR TITLE
Update rubocop to 1.56.3 and ruby to 3.2.2

### PR DESCRIPTION
**Pull request by BrianHawley**
Ruby 2 is EOL, and can have trouble installnig on modern systems.

- Updated ruby in .ruby-version and Dockerfile.
- No need to install an old version of bundler in Dockerfile.
- Removed the standard gem (see #357).
- General bundle update.
- Updated docs.

### CODE REVIEW

**Comment by BrianHawley** [comment]
@fede-moya or @filipesperandio could you review and merge?

**Comment by maxrosecollins** [comment]
@BrianHawley @fede-moya @filipesperandio Is there any timeline on this being merged? We cannot use codeclimate anymore since we updated ruby and rubocop.

**Comment by hampld** [comment]
> @BrianHawley @fede-moya @filipesperandio Is there any timeline on this being merged? We cannot use codeclimate anymore since we updated ruby and rubocop.

I'd also be very interested in the timeline for this, and in general a timeline for releasing rubocop updates. Having to open an issue for every rubocop release and then hoping it might be picked up (usually it doesn't!) can't be "the standard process", right?

**Comment by rebeccafae** [comment]
Bump!

**Comment by hampld** [comment]
bump ...

**Pull request merged**
