### PR TITLE
Update ruby 2.6.5-alpine3.11 image

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by krzysiek1507** [comment]
It doesn't have to be merged to the 0.80 channel. Just wanted to upgrade both Ruby and alpine.
If you will remember to upgrade the image with 0.81 channel release, we can closed this one.

**Comment by filipesperandio** [comment]
Let's keep this open. Updated the channel, so when we actually have a 0.81 we make this part of the _upgrade_ plan.

**Comment by filipesperandio** [comment]
Can you rebase with that branch when you get a chance?

**Comment by krzysiek1507** [comment]
My branch is up-to-date with `channel/0-80` but `channel/0-81` is behind `channel/0-80`, so you need to rebase and push `channel/0-81`.

**Comment by krzysiek1507** [comment]
Ok, I just dropped the commit with 0.80.1 update.

**Pull request merged**
