### PR TITLE
Add RuboCop RSpec

### PR DESCRIPTION
**Pull request by Aigeruth**

### CODE REVIEW

**Comment by GordonDiggs** [comment]
@Aigeruth Can you explain this change a bit? What does this accomplish and what is the benefit of the change?

**Comment by Aigeruth** [comment]
@GordonDiggs [rubocop-rspec](https://github.com/nevir/rubocop-rspec) is a RuboCop extension, that we are using for our project. Our `.rubocop.yml` contains the `require: rubocop-rspec` line, so RuboCop tries to require this gem, but it fails.

Currently I receive this error:
```sh
✗ docker run \
>   --interactive --tty --rm \
>   --env CODE_PATH="$PWD" \
>   --volume "$PWD":/code \
>   --volume /var/run/docker.sock:/var/run/docker.sock \
>   --volume /tmp/cc:/tmp/cc \
>   codeclimate/codeclimate analyze
Starting analysis
Running rubocop: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr "/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rubocop-rspec (LoadError)\n\tfrom /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/config_loader.rb:31:in `block in load_file'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/config_loader.rb:31:in `each'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/config_loader.rb:31:in `load_file'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/config_loader.rb:85:in `configuration_from_file'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/config_store.rb:40:in `for'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:112:in `excluded_dirs'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:90:in `find_files'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:60:in `target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:31:in `find'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/runner.rb:41:in `find_target_files'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:18:in `block in run'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `chdir'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `run'\n\tfrom /usr/src/app/bin/codeclimate-rubocop:6:in `<main>'\n"
```

**Comment by john-griffin** [comment]
Also have this problem. `rubocop-rspec` is a set of custom cops provided as a gem. https://github.com/bbatsov/rubocop#known-custom-cops

As it's configured from `.rubocop.yml` it tries to load the gem but its not available. This is currently preventing my app from using the engine.

**Comment by GordonDiggs** [comment]
Thank you! This should be available in the CLI now if you run `codeclimate engines:install` or `docker pull codeclimate/codeclimate-rubocop`

**Pull request merged**
