### PR TITLE
Add channel/rubocop-1-11-0

### PR DESCRIPTION
**Pull request by timlkelly**
I am unsure which branch to target, does a `codeclimate:channel/rubocop-1-11-0` branch need to be made on the base repository?
I am currently targeting `channel/rubocop-1-10-0` because that is where I branched from.

### CODE REVIEW

**Comment by fede-moya** [comment]
Hey @timlkelly 👋🏼 , you should target [rubocop-1-11-0](https://github.com/codeclimate/codeclimate-rubocop/tree/channel/rubocop-1-11-0)

**Comment by timlkelly** [comment]
@fede-moya updated. 

If you can create channels for `1.12.1`, `1.13.0`, `1.14.0`, `1.15.0`, `1.16.1`, `1.17.0`, and `1.18.2`, I can update for those channels as well to catch up to the latest versions.

**Comment by fede-moya** [comment]
@timlkelly done 🙌🏼

**Comment by fede-moya** [comment]
@timlkelly can you rebase this one ?

**Comment by timlkelly** [comment]
@fede-moya updated.

**Review by fede-moya — APPROVED** [review]

**Pull request merged**
