### PR TITLE
Updated channel and documentation to Rubocop v0.84.0

### PR DESCRIPTION
**Pull request by DanielWright**
This PR proposes to update the Rubocop integration to support v0.84.0.

### CODE REVIEW

**Comment by ckhall** [comment]
rubocop is at 0.85 as of a couple days ago.

**Comment by DanielWright** [comment]
The 0.85 release of Rubocop is breaking the build due to https://github.com/rubocop-hq/rubocop/issues/8077. A fix has been merged, but not released yet. I'll leave it up to Top Men whether to merge this in the meantime, or wait for the next release.

**Comment by DanielWright** [comment]
Closing this, as it's superseded by #238.

**Comment by krzysiek1507** [comment]
I think this should also be merged? @filipesperandio

**Comment by krzysiek1507** [comment]
CC: @noelia-lencina

**Comment by filipesperandio** [comment]
Sorry @DanielWright @krzysiek1507 we have some work requiring us some more energy. We will get back to these upgrades soon.

**Pull request closed without merging**
