### PR TITLE
Update rubocop to 1.60.2

### PR DESCRIPTION
**Pull request by BrianHawley**
- General bundle update.
- Update the docs too.
- Fix a rubocop gem ordering complaint in Gemfile.

### CODE REVIEW

**Comment by BrianHawley** [comment]
@fede-moya or @filipesperandio could you review and merge?

**Comment by BrianHawley** [comment]
@RubyBrewsday you merged the last update. Could you merge this one?

**Comment by rebeccafae** [comment]
Can someone please merge this?

And thank you @BrianHawley for getting these new channels made for the latest versions. It is much appreciated!

**Comment by BrianHawley** [comment]
Unfortunately, @rebeccafae, I can't get them to make new channels for the new versions. That's why I got them to make channel/beta, so I can at least make PRs to get an evergreen branch updated.

I'm hoping to eventually get rid of the channel branch system, but I haven't yet allocated the time to do the work.

**Comment by rebeccafae** [comment]
@BrianHawley do you have a way of using the branch while is it still in the PR? I'd love to be able to start using this.

**Comment by BrianHawley** [comment]
@rebeccafae I'm not aware of how to use stuff in the codeclimate service or CLI while it's in an unmerged PR.

What I tend to do is set `channel: beta` for rubocop in my .codeclimate.yml file, just so I can keep as up to date as possible with the service - it is at the last PR, afaik. But to really use rubocop, I use it locally in my own codebase.

I don't use the other channels, because the current method they use to make channels is to create a branch for each channel here, and I can't practically get such branches created. The solution to this would be to change how they do channels for rubocop, both here and in the main codeclimate repository. I have some ideas about how to do this, but haven't had the time, yet.

**Comment by rebeccafae** [comment]
Since we're past the holidays, any chance someone could review and merge this? @RubyBrewsday @fede-moya @filipesperandio

**Comment by filipesperandio** [comment]
Hey, @rebeccafae ! I am away from the project a while now, but will ask the guys to take a look when they can.
@fede-moya would you have some availability?

**Comment by rebeccafae** [comment]
@fede-moya any chance you are able to review this?

**Comment by kayodeadeniyi** [comment]
We are waiting on this version of the channel to be merged in. Any chance we can get this soon?

**Comment by rebeccafae** [comment]
Since this is only going to the beta branch and not an official channel, is there a reason this can't just be merged as-is without a thorough review? @fede-moya @filipesperandio

**Comment by fede-moya** [comment]
Yes, I'm sorry.

**Pull request merged**
