### PR TITLE
Bump RuboCop to 0.47.1

### PR DESCRIPTION
**Pull request by maxjacobson**
Compare: https://github.com/bbatsov/rubocop/compare/v0.46.0...v0.47.1

The change in the Dockerfile is motivated by this issue and it's
suggested workaround: https://github.com/sickill/rainbow/issues/48

I generated the docs outside of docker because the rake task doesn't
currently work inside docker. I think that's fine.

### CODE REVIEW

**Comment by maxjacobson** [comment]
@wfleming Ah shoot, opened prematurely. Analysis errors in local QA. Will re-ping when I understand it better

**Comment by maxjacobson** [comment]
@wfleming OK re-opened with the fix in a separate commit for reviewing convenience. Tests pass and local QA look good, so I think I'm going to just go forward with a squash and merge.

**Comment by wfleming** [comment]
Seems fine if you're confident that internal change is tested/sufficiently QAed.

**Comment by maxjacobson** [comment]
Cool. Going for it

**Pull request merged**
