### PR TITLE
Bump rubocop to 0.37.2

### PR DESCRIPTION
**Pull request by jpignata**
* Bump to Rubocop 0.37.1. See: https://github.com/bbatsov/rubocop/blob/master/CHANGELOG.md
* Introduce SourceFile
* Rename ViolationDecorator to Issue
* Move presentation concerns into Issue
* Refine remediation point names to better match what they represent
* Move from minitest to rspec
* Begin work to improve coverage

@codeclimate/review

### CODE REVIEW

**Comment by jpignata** [comment]
Broke the camel's back in `CC::Engine::Rubocop`, apparently.

**Comment by wfleming** [comment]
I'm ok with ignoring that line count if you want to, but I also see a fairly easy extraction: this class right now covers all of:

1. Walking  `include_paths` for files to analyze
2. Getting analysis results on those file from Rubocop
3. Formatting said results as Issue JSON to emit on stdout.

Item 3 by itself is ~35 lines, and feels like a distinct responsibility that we already organize as its own class in other engines. Personally, that's where I'd make the change.

**Comment by jpignata** [comment]
@wfleming Nah, we should fix it. It does way too much. I'm extracting things from it now but in doing so I'm also seeing language that doesn't align with our domain very well and a lack of coverage around fiddly bits like remediation point generation. I want to spend a bit more time tackling those issues before requesting re-review.

**Comment by jpignata** [comment]
@wfleming Ready for :eyes: when you have a sec.

**Comment by jpignata** [comment]
Interestingly they've deprecated one of the cops and if referenced in the rubocop.yml, the anaysis will fial:

```
Running rubocop: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr 
/usr/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/config.rb:250:in `reject_obsolete_cops': The `Style/TrailingComma` cop no longer exists. Please use `Style/TrailingCommaInLiteral` and/or `Style/TrailingCommaInArguments` instead. (RuboCop::ValidationError)
(configuration found in /code/.rubocop.yml)
```

Our default configuration references `Style/TrailingComma`.

**Comment by jpignata** [comment]
The Code Climate issues are due to changing cop names (`Style/MultilineOperationIndentation` and `Style/TrailingComma`).

**Comment by wfleming** [comment]
This looks good to me. If we can get the updated default config out, I'd say ship it.

**Comment by jpignata** [comment]
Going to let this sit for a bit until the larger CLI change is out.

**Comment by ABaldwinHunter** [comment]
Hm, surprised by CC issues; I thought we prefer including a comma after last item in hash.

**Comment by wfleming** [comment]
@ABaldwinHunter I believe it's because JP updated the config for the new version, but of course that new version isn't actually running against the repo yet. The new version changed several rule names.

**Comment by jpignata** [comment]
This is ready for another look, @codeclimate/review.

**Comment by GordonDiggs** [comment]
LGTM

**Comment by wfleming** [comment]
From a quick reading of recent changes in `whitequark/parser`, and confirming that we are on the most recent version of that gem now, I *think* this might give us support for Ruby 2.3 syntax. Worth testing a bit more specifically to see if that's worth promoting on release.

**Comment by jpignata** [comment]
It does give us support for Ruby 2.3 syntax. I'll merge this once I have a
changelog draft.

**Comment by wfleming** [comment]
:fireworks:

**Comment by ABaldwinHunter** [comment]
@jpignata nice work! reminder to update [doc](https://docs.codeclimate.com/docs/rubocop) in addition to changelog once all set.

**Comment by rheaton** [comment]
Was this just deployed? Rubocop upgrade breaks older rubocop.yml (we see analysis errors now)

**Comment by rheaton** [comment]
P.S. hi JP. :wave:

**Comment by jpignata** [comment]
Hey, @rheaton! Yes, we just deployed this earlier this afternoon. Some configuration syntax moved around between the RuboCop versions which require some tweaks to your config. If you check the build itself, the STDERR output should detail the changes necessary. Can you let me know if you see this output and if it's helpful?

**Comment by rheaton** [comment]
Yes, we see it! It's slow going through since it's one error at a time. Any suggestions?

**Comment by jpignata** [comment]
It's probably giving you separate tranches of output for each of RuboCop's validations. I'd either use the Code Climate CLI or install RuboCop 0.37.2 locally and tweak your configuration there before re-pushing.

**Comment by rheaton** [comment]
@jpignata Thanks!

**Comment by jpignata** [comment]
@rheaton Sorry for the trouble!

**Comment by rheaton** [comment]
NP! We were actually bemoaning that it was an older version of rubocop this morning. :grin: Love those Friday deploys, haha. :trollface:

**Pull request merged**
