### PR TITLE
Upgrade to RuboCop 0.47.1 (again)

### PR DESCRIPTION
**Pull request by maxjacobson**
This needs to be shipped in tandem with https://github.com/codeclimate/codeclimate/pull/563

### CODE REVIEW

**Comment by raulmarcosl** [comment]
Please, be careful with this upgrades. Yesterday our builds were failing due to cop naming problems, so we upgrade our rubocop config to `0.47.1`, but then you reverted the changes, and our new config is failing, so we had to revert it.

IMO, it would be great to be able to force a rubocop version to avoid this problems.

**Comment by tarebyte** [comment]
Friendly bump, would be lovely to have this merged in 😄

**Comment by colszowka** [comment]
Make that 0.48.1 please :)

In that version Rubocop changed `Rubocop/Style/PercentLiteralDelimiters` to be `[]` by default, which broke our code climate reporting (on the bundled 0.46) while locally everything's green on the fresh version. Additionally, the bundled 0.46 version does not seem to acknowledge the `PreferredDelimiters: / default: "[]"` setting, so we had to disable the cop in code climate for the time being.

**Comment by trautwein** [comment]
Another friendly bump 😄  Any update on this?

**Comment by kjg** [comment]
With the vast number of differences between rubocop versions, it would be awesome if we could somehow specific which version we'd like codeclimate to run (to match our local gem version)

**Comment by deivid-rodriguez** [comment]
Hei! Not sure what's blocking this, but there's this [tool](https://github.com/pocke/mry) to migrate rubocop's config between versions. Just mentioning in case it could help.

**Comment by maxjacobson** [comment]
Just an update:

Thanks everyone for your patience on this.

If you're interested in using RuboCop 0.48.1 on Code Climate, you can now. We've made it available as a channel. You can switch to it by adding the following to your `.codeclimate.yml`:

```yaml
engines:
  rubocop:
    enabled: true
    channel: rubocop-0-48
```

The default channel is still running RuboCop 0.46.0 as of today.

I'm going to close this PR for now.

(btw, thanks for sharing mry, @deivid-rodriguez, that's pretty neat and may help us out in the future)

**Pull request closed without merging**
