### PR TITLE
Update rubocop to 1.64.1

### PR DESCRIPTION
**Pull request by BrianHawley**
- General bundle update.
- Update the docs too.
- Add rubocop-rspec_rails because its cops have been moved out of rubocop-rspec; rubocop-capybara and rubocop-factory_bot were added earlier for the same reason.
- Add rubocop-rails-omakase for those who want a less prescriptive rubocop config.
- Add `require "ostruct"` to a couple test files using OpenStruct.

### CODE REVIEW

**Comment by BrianHawley** [comment]
@fede-moya could you merge this one? It's just `bundle update` and `rake docs:scrape`.

**Comment by rebeccafae** [comment]
Sorry, I don't know of a better place to ask this. What is the process for getting a new channel version branch off of the beta so that we can have another locked version?

**Comment by BrianHawley** [comment]
@fede-moys could you merge this one? It includes fixes for Rails 7.1 projects, so it's a critical upgrade.

**Comment by fede-moya** [comment]
I've confirmed the plan by running it through this branch, which is clean, at least for the ce-test-report-creator ECS service. Additionally, the running theory is that this is a good long-term solution that should allow us to continue supporting large customers like Benchling. We can circle back if anyone disagrees.

**Comment by fede-moya** [comment]
Thanks, will release the change soon!

**Pull request merged**
