### PR TITLE
[Channel 0-88] Update rubocop-rails (2.7.1)

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by kulas115** [comment]
Hey Guys 👋🏼  Is there some problem with this PR so it's open for 13 days now? 

I've just noticed that I got `rubocop` checks failing on `codeclimate` since I've added new cops introduced in `rubocop-rails 2.7.0` but it was never merged to any of your channels.

This PR wants to merge update to branch `rubocop-0-88` but the latest one is `rubocop-0-89` so I guess it should be added there as well.

Thanks for looking into this 🙇🏼‍♂️

**Comment by krzysiek1507** [comment]
Create a PR #255 for 0.89.

**Comment by kulas115** [comment]
> Created a PR #255 for 0.89.

Shouldn't you also explicitly enable all cops added in the latest `rubocop-rails` versions? 

Eventhough https://github.com/codeclimate/codeclimate-rubocop/pull/255 was merge to master I still get errors when codeclimate is running `rubocop` about missing cops:
```
unrecognized cop Rails/FindById found in .rubocop.yml, 
unrecognized cop Rails/ActiveRecordCallbacksOrder found in .rubocop.yml, 
unrecognized cop Rails/RenderPlainText found in .rubocop.yml, 
unrecognized cop Rails/DefaultScope found in .rubocop.yml, 
unrecognized cop Rails/MatchRoute found in .rubocop.yml, 
unrecognized cop Rails/WhereExists found in .rubocop.yml, 
unrecognized cop Rails/RenderInline found in .rubocop.yml, 
unrecognized cop Rails/MailerName found in .rubocop.yml, 
unrecognized cop Rails/ShortI18n found in .rubocop.yml, 
unrecognized cop Rails/Inquiry found in .rubocop.yml, 
unrecognized cop Rails/PluckInWhere found in .rubocop.yml, 
unrecognized cop Rails/NegateInclude found in .rubocop.yml, 
unrecognized cop Rails/Pluck found in .rubocop.yml, 
unrecognized cop Rails/PluckId found in .rubocop.yml,
unrecognized cop RSpec/MultipleMemoizedHelpers found in .rubocop.yml
```

**Comment by krzysiek1507** [comment]
It looks like `channel-0-89` uses an old image. It should use b721.
```
determining required images
docker pull registry.prod.codeclimate.net/codeclimate/codeclimate-rubocop:b718
```

@filipesperandio any ideas?

**Comment by filipesperandio** [comment]
@krzysiek1507 @kulas115 for which repo you are seeing this issue?

**Comment by filipesperandio** [comment]
Also merging this, sorry it took so long.

**Comment by filipesperandio** [comment]
(feel free to tag me as reviewer in the future, might catch my attention more easily)

**Comment by krzysiek1507** [comment]
@filipesperandio will do! If you have any other tips how we can help with upgrading rubocop, please let us know!

**Comment by krzysiek1507** [comment]
When the new images are available on CodeClimate? On `channel-0-88` it still uses `docker pull registry.prod.codeclimate.net/codeclimate/codeclimate-rubocop:b712` instead of b723.

**Comment by filipesperandio** [comment]
I have a clue now, there is something I have to dig in the repos upgrade process. I will keep you posted.

**Comment by filipesperandio** [comment]
> When the new images are available on CodeClimate? On channel-0-88 it still uses docker pull registry.prod.codeclimate.net/codeclimate/codeclimate-rubocop:b712 instead of b723.

We have to trigger an internal upgrade process that tell repos they will use a most recent image, differently from the CLI, that automatically uses the latest image from each plugin/channel.
We are spacing out those upgrades, but I found a bug we recently introduced, fix is on the way.

**Comment by filipesperandio** [comment]
We should be good. Let me know if you still see issues with new builds.

**Comment by krzysiek1507** [comment]
It works! Thanks!

**Pull request merged**
